[package]
authors = ["Evan Stoll <evanjsx@gmail.com>"]
edition = "2018"
name = "rrbg"
version = "0.1.0"
[dependencies]
dotenv = "0.13.0"
env_logger = "0.6.0"
envy = "0.3.3"
futures-preview = "0.2.2"
glob = "0.2.11"
imagesize = "0.6.0"
log = "0.4.6"
rand = "0.6.5"
rayon = "1.0.3"
serde = "1.0.88"
serde_derive = "1.0.88"

[dependencies.x11]
default-features = true
features = ["xlib", "xrandr"]
version = "2.18.1"
[profile.release]
lto = "thin"
opt-level = "z"
