[package]
authors = ["Evan Stoll <evanjsx@gmail.com>"]
edition = "2018"
name = "rrbg"
version = "0.1.0"
[dependencies]
dotenv = "0.14.1"
env_logger = "0.6.2"
envy = "0.4.0"
glob = "0.3.0"
imagesize = "0.8.0"
log = "0.4.6"
rand = "0.7.0"
rayon = "1.1.0"
serde = "1.0.94"
serde_derive = "1.0.95"
dirs = "2.0.1"
failure = "0.1.5"
serde_json = "1.0.40"
clap = { version = "2.33.0", features = ["yaml"] }
sdl2 = "0.32.2"

[profile.release]
lto = "thin"
opt-level = "z"
